services:
  robot:
    build:
      context: robot
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - robot
    ports:
      - "8000:8000"
    environment:
      - RUNENV=docker
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://backend:8000
      - VITE_SERVER_URL=http://localhost:8000
